import 'dart:io';
import 'package:flutter/material.dart';
import '../../../features/terminal/terminal_capabilities.dart';
import '../packages/package_manager.dart';
import '../storage/disk_usage_analyzer.dart';
import '../system/system_monitor.dart';
import '../windows/zion_file_manager.dart';
import '../wifi/zion_wifi_panel.dart';
import '../backup/backup_manager.dart';
import '../security_center/security_center.dart';
import '../../../features/terminal/terminal_screen.dart';
import '../developer/developer_center.dart';
class ZionControlCenter extends StatefulWidget { const ZionControlCenter({super.key}); @override State<ZionControlCenter> createState()=>_ZionControlCenterState(); }
class _ZionControlCenterState extends State<ZionControlCenter> {
 bool _loading=true; final List<_Capability> _capabilities=[];
 @override void initState(){super.initState();_refresh();}
 Future<void> _refresh() async { if(mounted)setState(()=>_loading=true); final runtime=await TerminalCapabilities.describeRuntime(); final shell=await TerminalCapabilities.describeRuntime().then((runtime)=>runtime.contains('AVAILABLE')); final git=await _probe('git',['--version']); final python=await _probe('python',['--version']); final storage=await _probe('df',['-h','/']); if(!mounted)return; setState((){_capabilities..clear()..add(_Capability('Terminal / PTY',shell,'Zion Userland runtime available'))..add(_Capability('Zion runtime',runtime.contains('AVAILABLE'),runtime))..add(_Capability('Git',git,git?'Git executable detected':'Not installed in active runtime'))..add(_Capability('Python',python,python?'Python executable detected':'Not installed in active runtime'))..add(_Capability('Storage',storage,storage?'Real df telemetry available':'Storage telemetry unavailable'));_loading=false;});}
 Future<bool> _probe(String command,List<String> args)async{try{return (await Process.run(command,args,runInShell:false).timeout(const Duration(seconds:3))).exitCode==0;}catch(_){return false;}}
 void _open(Widget page)=>Navigator.of(context).push(MaterialPageRoute<void>(builder:(_)=>page));
 @override Widget build(BuildContext context){final ready=_capabilities.where((c)=>c.available).length; return Scaffold(backgroundColor:const Color(0xFF070B10),appBar:AppBar(title:const Text('Zion Control Center'),backgroundColor:const Color(0xFF101923),actions:[IconButton(onPressed:_loading?null:_refresh,icon:const Icon(Icons.refresh))]),body:RefreshIndicator(onRefresh:_refresh,child:ListView(padding:const EdgeInsets.all(16),children:[
 Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(borderRadius:BorderRadius.circular(18),border:Border.all(color:const Color(0xFF00BCD4)),color:const Color(0xFF0D1720)),child:Row(children:[const Icon(Icons.hub,color:Color(0xFF00BCD4),size:42),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('ZION OS',style:TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.w700)),const SizedBox(height:4),Text(_loading?'Checking real runtime capabilities…':'$ready/${_capabilities.length} core capabilities available',style:const TextStyle(color:Colors.white70))]))])),
 const SizedBox(height:14),const Text('Core distribution',style:TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:10),
 GridView.count(crossAxisCount:MediaQuery.of(context).size.width>700?4:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisSpacing:10,mainAxisSpacing:10,childAspectRatio:1.45,children:[_action(Icons.terminal,'Terminal 2.0',const TerminalScreen()),_action(Icons.inventory_2,'Packages',const PackageManager()),_action(Icons.folder_copy,'File Manager',const ZionFileManager()),_action(Icons.wifi_find,'Network Center',const ZionWifiPanel()),_action(Icons.monitor_heart,'System Monitor',const SystemMonitor()),_action(Icons.security,'Security Center',const SecurityCenter()),_action(Icons.backup,'Backup / Restore',const BackupManager()),_action(Icons.storage,'Storage',const DiskUsageAnalyzer()),_action(Icons.code,'Developer',const DeveloperCenter())]),
 const SizedBox(height:18),const Text('Live capabilities',style:TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:10),if(_loading)const Center(child:Padding(padding:EdgeInsets.all(30),child:CircularProgressIndicator())) else ..._capabilities.map((c)=>ListTile(leading:Icon(c.available?Icons.check_circle:Icons.radio_button_unchecked,color:c.available?Colors.greenAccent:Colors.orangeAccent),title:Text(c.name,style:const TextStyle(color:Colors.white)),subtitle:Text(c.detail,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white60))))])));}
 Widget _action(IconData icon,String title,Widget page)=>Card(color:const Color(0xFF101923),child:InkWell(onTap:()=>_open(page),child:Padding(padding:const EdgeInsets.all(12),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,color:const Color(0xFF00BCD4),size:28),const SizedBox(height:8),Text(title,textAlign:TextAlign.center,style:const TextStyle(color:Colors.white))]))));
}
class _Capability{final String name;final bool available;final String detail;const _Capability(this.name,this.available,this.detail);}