import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class ZionFileManager extends StatefulWidget { const ZionFileManager({super.key}); @override State<ZionFileManager> createState()=>_ZionFileManagerState(); }
class _ZionFileManagerState extends State<ZionFileManager> {
 static const _channel=MethodChannel('zion.os/storage'); String? _rootUri; String _title='External Storage'; List<Map<String,dynamic>> _items=const []; final List<Map<String,String>> _history=[]; bool _loading=false; String? _error;
 Future<void> _pickStorage() async { setState((){_loading=true;_error=null;}); try { final r=Map<String,dynamic>.from(await _channel.invokeMethod('pickTree') as Map); if(r['status']=='AVAILABLE'&&r['uri'] is String){_rootUri=r['uri'] as String;_history..clear()..add({'uri':_rootUri!,'name':r['name']?.toString()??'External storage'});_title=_history.last['name']!;await _load(_rootUri!);}else if(mounted)setState(()=>_error='لم يتم اختيار وحدة تخزين خارجية.'); }on PlatformException catch(e){if(mounted)setState(()=>_error=e.message??e.code);}finally{if(mounted)setState(()=>_loading=false);}}
 Future<void> _load(String uri) async {setState((){_loading=true;_error=null;});try{final r=Map<String,dynamic>.from(await _channel.invokeMethod('listTree',{'uri':uri}) as Map);final raw=(r['items'] as List? ?? const []);final items=raw.map((e)=>Map<String,dynamic>.from(e as Map)).toList();if(mounted)setState(()=>_items=items);}on PlatformException catch(e){if(mounted)setState(()=>_error=e.message??e.code);}finally{if(mounted)setState(()=>_loading=false);}}
 Future<void> _open(Map<String,dynamic> item)async{if(item['isDirectory']!=true)return;final uri=item['uri']?.toString();if(uri==null)return;_history.add({'uri':uri,'name':item['name']?.toString()??'Folder'});setState(()=>_title=_history.last['name']!);await _load(uri);}
 Future<void> _back()async{if(_history.length<=1)return;_history.removeLast();setState(()=>_title=_history.last['name']!);await _load(_history.last['uri']!);}
 Future<void> _delete(Map<String,dynamic> item)async{final uri=item['uri']?.toString();if(uri==null)return;final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Delete'),content:Text('حذف '+(item['name']?.toString()??'هذا العنصر')+'؟'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Delete'))]));if(ok!=true)return;await _channel.invokeMethod('delete',{'uri':uri});await _load(_history.last['uri']!);}
 @override Widget build(BuildContext context){return Scaffold(backgroundColor:const Color(0xFF070B10),appBar:AppBar(title:Text(_title),backgroundColor:const Color(0xFF101923),leading:IconButton(onPressed:_history.length>1?_back:null,icon:const Icon(Icons.arrow_back)),actions:[IconButton(onPressed:_pickStorage,icon:const Icon(Icons.sd_storage)),IconButton(onPressed:_rootUri==null?null:()=>_load(_history.last['uri']!),icon:const Icon(Icons.refresh))]),body:_rootUri==null?Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.sd_storage,size:64,color:Colors.white38),const SizedBox(height:16),const Text('اختر وحدة التخزين الخارجية أو بطاقة SD عبر Android SAF.',textAlign:TextAlign.center),const SizedBox(height:12),FilledButton.icon(onPressed:_pickStorage,icon:const Icon(Icons.folder_open),label:const Text('اختيار التخزين'))])):_loading?const Center(child:CircularProgressIndicator()):_error!=null?Center(child:Text(_error!,style:const TextStyle(color:Colors.redAccent))):_items.isEmpty?const Center(child:Text('المجلد فارغ')):ListView.builder(itemCount:_items.length,itemBuilder:(_,i){final x=_items[i];final dir=x['isDirectory']==true;return ListTile(leading:Icon(dir?Icons.folder:Icons.insert_drive_file,color:dir?Colors.amber:Colors.white70),title:Text(x['name']?.toString()??'',overflow:TextOverflow.ellipsis),subtitle:Text(dir?'مجلد':((x['size']??'').toString()+' bytes')),onTap:()=>_open(x),onLongPress:()=>_delete(x));}));}
}