import 'dart:async';
import 'package:flutter/material.dart';
import '../../core/services/system_metrics.dart';

class SystemMonitor extends StatefulWidget { const SystemMonitor({super.key}); @override State<SystemMonitor> createState()=>_SystemMonitorState(); }
class _SystemMonitorState extends State<SystemMonitor> { SystemMetrics? _metrics; Timer? _timer; bool _loading=true;
 @override void initState(){super.initState();_refresh();_timer=Timer.periodic(const Duration(seconds:2),(_)=>_refresh());}
 @override void dispose(){_timer?.cancel();super.dispose();}
 Future<void> _refresh() async {try{final value=await SystemMetrics.read();if(mounted)setState((){_metrics=value;_loading=false;});}catch(_){if(mounted)setState(()=>_loading=false);}}
 String _bytes(int value){if(value<1024*1024)return '${value~/1024} KB';if(value<1024*1024*1024)return '${(value/(1024*1024)).toStringAsFixed(1)} MB';return '${(value/(1024*1024*1024)).toStringAsFixed(1)} GB';}
 @override Widget build(BuildContext context){final m=_metrics;final children=m==null?<Widget>[]:<Widget>[_card('CPU',m.cpuPercent,'/proc/stat'),_card('Memory',m.memoryPercent,'${_bytes(m.memoryUsedBytes)} / ${_bytes(m.memoryTotalBytes)}'),_card('Storage',m.storagePercent,'Filesystem /'),_card('Uptime',null,'${m.uptime.inHours}h ${m.uptime.inMinutes%60}m ${m.uptime.inSeconds%60}s')];return Scaffold(backgroundColor:const Color(0xFF070B10),appBar:AppBar(title:const Text('System Monitor'),backgroundColor:const Color(0xFF101923),actions:[IconButton(onPressed:_refresh,icon:const Icon(Icons.refresh))]),body:_loading&&m==null?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16),children:children));}
 Widget _card(String title,double? value,String detail){return Card(color:const Color(0xFF101923),margin:const EdgeInsets.only(bottom:12),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Text(title,style:const TextStyle(color:Colors.white,fontSize:17,fontWeight:FontWeight.bold)),const Spacer(),if(value!=null)Text('${value.toStringAsFixed(1)}%',style:const TextStyle(color:Color(0xFF00BCD4),fontSize:22,fontWeight:FontWeight.bold))]),const SizedBox(height:8),if(value!=null)LinearProgressIndicator(value:(value/100).clamp(0,1).toDouble()),const SizedBox(height:8),Text(detail,style:const TextStyle(color:Colors.white54,fontSize:11))])));}
}