import 'dart:io';
import 'package:flutter/material.dart';

class DeveloperCenter extends StatefulWidget { const DeveloperCenter({super.key}); @override State<DeveloperCenter> createState()=>_DeveloperCenterState(); }
class _DeveloperCenterState extends State<DeveloperCenter> { final Map<String,bool> _tools={}; bool _loading=true; String _output='';
 @override void initState(){super.initState();_probe();}
 Future<void> _probe() async {final names=['git','python','node','dart','flutter','ssh'];final values=<String,bool>{};for(final n in names){try{values[n]=(await Process.run(n,['--version'],runInShell:false).timeout(const Duration(seconds:2))).exitCode==0;}catch(_){values[n]=false;}}if(mounted)setState((){_tools..clear()..addAll(values);_loading=false;});}
 Future<void> _run(String command,List<String> args) async {try{final r=await Process.run(command,args,runInShell:false);if(mounted)setState(()=>_output='exit=${r.exitCode}\n${r.stdout}\n${r.stderr}');}catch(e){if(mounted)setState(()=>_output=e.toString());}}
 @override Widget build(BuildContext context){return Scaffold(backgroundColor:const Color(0xFF070B10),appBar:AppBar(title:const Text('Zion Developer Center'),backgroundColor:const Color(0xFF101923),actions:[IconButton(onPressed:_probe,icon:const Icon(Icons.refresh))]),body:ListView(padding:const EdgeInsets.all(16),children:[const Text('Real development environment',style:TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:8),const Text('Only installed executables are reported as available.',style:TextStyle(color:Colors.white54)),const SizedBox(height:12),if(_loading)const Center(child:CircularProgressIndicator()) else ..._tools.entries.map((e)=>ListTile(leading:Icon(e.value?Icons.check_circle:Icons.radio_button_unchecked,color:e.value?Colors.greenAccent:Colors.orangeAccent),title:Text(e.key,style:const TextStyle(color:Colors.white)),trailing:Text(e.value?'AVAILABLE':'NOT INSTALLED',style:TextStyle(color:e.value?Colors.greenAccent:Colors.orangeAccent,fontSize:11)))),const Divider(color:Colors.white24),Wrap(spacing:8,children:[OutlinedButton(onPressed:()=>_run('git',['--version']),child:const Text('Git')),OutlinedButton(onPressed:()=>_run('python',['--version']),child:const Text('Python')),OutlinedButton(onPressed:()=>_run('node',['--version']),child:const Text('Node')),OutlinedButton(onPressed:()=>_run('ssh',['-V']),child:const Text('SSH'))]),if(_output.isNotEmpty)Padding(padding:const EdgeInsets.only(top:16),child:SelectableText(_output,style:const TextStyle(color:Colors.white70,fontFamily:'monospace',fontSize:11))) ]));}
}