import 'dart:io';
import 'package:flutter/material.dart';
import '../../../core/userland/zion_pkg.dart';
import '../../../core/userland/zion_repository.dart';

class PackageManager extends StatefulWidget { const PackageManager({super.key}); @override State<PackageManager> createState()=>_PackageManagerState(); }
class _PackageManagerState extends State<PackageManager> {
  final _nameController=TextEditingController(), _searchController=TextEditingController();
  List<PackageInfo> _packages=const []; Map<String,PackageStatus> _tools=const {}; bool _loading=true; String _message='جارٍ فحص Zion Userland الحقيقي…';
  ZionPkg get _pkg => ZionPkg(repository: ZionRepository());
  @override void initState(){super.initState();_reload();}
  @override void dispose(){_nameController.dispose();_searchController.dispose();super.dispose();}
  Future<void> _reload() async { if(mounted)setState(()=>_loading=true); final tools=await _pkg.checkTools(); final packages=await _pkg.getInstalledPackages(); if(!mounted)return; setState((){_tools=tools;_packages=packages;_message=(tools['dpkg']==PackageStatus.available||tools['dpkg']==PackageStatus.installed)?'REAL Zion Userland • '+packages.length.toString()+' حزمة مسجلة.':'NOT_CONFIGURED: ثبّت Userland يحتوي على dpkg.';_loading=false;}); }
  Future<void> _run(Future<PkgResult> Function() op) async { if(mounted)setState(()=>_message='جارٍ تنفيذ العملية على Userland الحقيقي…'); final r=await op(); if(!mounted)return; setState(()=>_message=r.success?(r.message??'اكتملت العملية.'):('ERROR: '+(r.error??'unknown'))); await _reload(); }
  Future<void> _install()async{final n=_nameController.text.trim();if(n.isNotEmpty)await _run(()=>_pkg.installByName(n));}
  Future<void> _remove()async{final n=_nameController.text.trim();if(n.isNotEmpty)await _run(()=>_pkg.remove(n));}
  Future<void> _update({bool upgrade=false})async=>_run(upgrade?_pkg.upgrade:_pkg.update);
  Future<void> _cloneRepository()async{final url=_nameController.text.trim();if(!RegExp(r'^https://[^\s]+\.git/?$').hasMatch(url)){setState(()=>_message='أدخل رابط Git HTTPS ينتهي بـ .git.');return;}final git=ZionPkg.prefix+'/bin/git';if(!await File(git).exists()){setState(()=>_message='NOT_CONFIGURED: git غير مثبت داخل Userland.');return;}final name=url.split('/').last.replaceFirst(RegExp(r'\.git$'),'');final root=Directory(ZionPkg.prefix+'/share/zion-repos');await root.create(recursive:true);final target=root.path+'/'+name;if(await Directory(target).exists()){setState(()=>_message='المستودع موجود مسبقاً: '+name);return;}try{final r=await Process.run(git,['clone','--',url,target],runInShell:false);if(mounted)setState(()=>_message='exit='+r.exitCode.toString()+'\n'+r.stdout.toString()+'\n'+r.stderr.toString());}catch(e){if(mounted)setState(()=>_message='Git clone failed: '+e.toString());}}
  List<PackageInfo> get _filtered{final q=_searchController.text.trim().toLowerCase();return q.isEmpty?_packages:_packages.where((p)=>p.name.toLowerCase().contains(q)).toList(growable:false);}
  @override Widget build(BuildContext context){final ready=_tools['dpkg']==PackageStatus.available||_tools['dpkg']==PackageStatus.installed;return Scaffold(backgroundColor:Colors.black,appBar:AppBar(title:const Text('Zion Package Runtime'),backgroundColor:Colors.indigo.shade900,actions:[IconButton(onPressed:_loading?null:_reload,icon:const Icon(Icons.refresh))]),body:Column(children:[Container(width:double.infinity,margin:const EdgeInsets.fromLTRB(16,16,16,8),padding:const EdgeInsets.all(12),color:ready?Colors.green.shade900:Colors.orange.shade900,child:Text(_message,style:const TextStyle(color:Colors.white,fontSize:12))),Padding(padding:const EdgeInsets.symmetric(horizontal:16,vertical:4),child:TextField(controller:_nameController,style:const TextStyle(color:Colors.white),decoration:const InputDecoration(labelText:'اسم الحزمة أو رابط Git HTTPS',labelStyle:TextStyle(color:Colors.grey),border:OutlineInputBorder()))),Wrap(spacing:8,children:[ElevatedButton(onPressed:ready?_install:null,child:const Text('Install')),ElevatedButton(onPressed:ready?_remove:null,child:const Text('Remove')),ElevatedButton(onPressed:ready?()=>_update():null,child:const Text('Update')),ElevatedButton(onPressed:ready?()=>_update(upgrade:true):null,child:const Text('Upgrade')),OutlinedButton(onPressed:ready?_cloneRepository:null,child:const Text('Git clone'))]),Padding(padding:const EdgeInsets.all(16),child:TextField(controller:_searchController,style:const TextStyle(color:Colors.white),decoration:const InputDecoration(hintText:'ابحث في الحزم المثبتة…',hintStyle:TextStyle(color:Colors.grey),prefixIcon:Icon(Icons.search,color:Colors.grey),border:OutlineInputBorder()),onChanged:(_)=>setState((){}))),Expanded(child:_loading?const Center(child:CircularProgressIndicator()):_filtered.isEmpty?const Center(child:Text('لا توجد حزم مثبتة في Zion Userland.',style:TextStyle(color:Colors.grey))):ListView.builder(itemCount:_filtered.length,itemBuilder:(_,i){final p=_filtered[i];return ListTile(leading:const Icon(Icons.inventory_2,color:Colors.indigo),title:Text(p.name,style:const TextStyle(color:Colors.white)),subtitle:Text(p.version+' • '+p.architecture+' • '+p.source,style:const TextStyle(color:Colors.grey)));}))]));}
}